### ISSUE TITLE
Add part/quit messages and related info to puppet leave events

### ISSUE THREAD

**Issue by flukiluke** [hifi/heisenbridge#106]
Sometimes it's useful to know if/why someone on irc parted, or if their connection timed out etc.

Context from Heisenbridge room:
luke: Thoughts on having the bridge kick virtual irc users instead of just having them leave the room, so it can include the part/quit/kick message from irc?
hifi: it can include a message for leaves as well but it's 
not part of the call to leave a room in the API docs, matrix-appservice-irc does include the leave message for non-kicks 
that would actually remove the need for the bridge to announce nick changes as it could include that in the leave message

**Comment by hifi** [comment]
Adding to the suggested fix of making the bridge kick the users: doesn't work because the bridge is not necessarily an admin (in relaybot mode for one)

Just adding the reason to user leaving a room should work, though.
