### ISSUE TITLE
Passwords with quotes in them

### ISSUE THREAD

**Issue by w3bb** [hifi/heisenbridge#114]
I'm trying to set a password with a quote in it, but it keeps failing with this error in the console:

`ValueError: No closing quotation`

Is there some way to escape passwords with quotes in them?

**Comment by hifi** [comment]
It works like a shell so if you have a single quote use double quotes around your password, single quotes if your password has double quotes. Let me know if this works!

I'll fix up the parser to throw those errors within Matrix so it's more obvious if you have loose quotes around.

**Comment by hifi** [comment]
You can probably use backslash within quotes to get the desired result.

**Comment by w3bb** [comment]
That worked, thanks
