### ISSUE TITLE
Always use MXID hash by default for ident

### ISSUE THREAD

**Issue by dasJ** [hifi/heisenbridge#116]
As the title suggests, identd returns the first 8 characters of my MXID (?) instead of using my per-network username.

**Comment by hifi** [comment]
If you are an admin you can set per-network username and it takes precedence. The idea of the identd feature is to provide unique idents for users so I-lines can be requested.

It creates a hash of your MXID so it doesn't directly leak individual characters from it.

**Comment by hifi** [comment]
Changed from an issue to an action.

- default to mxid hash to prevent mxid conflicts and leaks
- ident configuration for admins (`IDENTCFG` in control room as admin command or something)
- allow setting global ident for any mxid
