### ISSUE TITLE
@heisenbridge user does not talk to federated users (when using conduit)

### ISSUE THREAD

**Issue by poVoq** [hifi/heisenbridge#136]
Might be related to this: https://github.com/hifi/heisenbridge/issues/134
(because it behaves very similar)

I have Heisenbridge working with the Conduit homeserver and it works fine with an admin users on the same Conduit homeserver.

But when I try to DM the @heisenbridge:myhomeserver user from an account on matrix.org the bot does not respond to the invitation.

I already tried setting the allow mask to both user and admin for the remote user account, but no difference.

**Comment by hifi** [comment]
Is your federation working in the first place? Can you DM other users, does debug log show something?

If it doesn't log anything it's either a Conduit or federation issue as each new invite will log something.

**Comment by poVoq** [comment]
Federation seems to work, I could for example invite the external user into the heisenbridge chat with another local user and Heisenbridge would even replay as if it was the user inviting.

**Comment by hifi** [comment]
You still need to check the debug output when you're trying to invite over federation to get an idea what's going on.
