### ISSUE TITLE
Give more detailed error messages

### ISSUE THREAD

**Issue by mpldr** [hifi/heisenbridge#155]
Hello,

while debugging I was regularly hindered by unprecise error messages such as:

> `WARNING:root:Request to HS failed, assuming it is down, retry 1/60...`

Why does it fail? A timeout, an error in name resolution, goblins stealing TCP packets? Enabling verbose mode does not give me more details either.

**Comment by hifi** [comment]
I suppose verbose logging could show the real error. I'll add it in the next point release.
