### ISSUE TITLE
Media URLs are incorrect

### ISSUE THREAD

**Issue by lenormf** [hifi/heisenbridge#156]
Hi,

This is similar to this issue https://github.com/matrix-org/matrix-appservice-irc/issues/154

I'm running Heisenbridge in a container, and the address of the homeserver I pass to it is an internal URL `http://synapse:8008/`. When I upload media to IRC, the resulting URL starts with `http://synapse:8008/`.

I'd like to have a way to specify an arbitrary domain instead, as is done with the upstream IRC appservice (`media_url` option).

Thanks!

**Comment by hifi** [comment]
Media URLs should work if your client configuration for your homeserver domain is correct. If you use delegation make sure you have a client `base_url` set in `/.well-known/matrix/client`.

If you have a networking setup that makes it impossible for it to work, then a configuration option is the only solution.

**Comment by lenormf** [comment]
Thanks for the quick reply!

The `base_url` option is configured correctly in Element (web client), and I do not use delegation.

After a quick look at the code, I had the intuition that I could work around my issue with having my base HTTPd serve `well-known` files, so Heisenbridge could pick up the right name?

I think an option is the right course, I could also run the bridge with the external address as parameter but the traffic would then go through the reverse proxy.

Thanks!

**Comment by hifi** [comment]
> After a quick look at the code, I had the intuition that I could work around my issue with having my base HTTPd serve `well-known` files, so Heisenbridge could pick up the right name?

If Heisenbridge can't connect to your httpd from within the container using the public domain of the MXID it hands out to the bridge itself then it can't access the well known file either on the same domain.

> I think an option is the right course, I could also run the bridge with the external address as parameter but the traffic would then go through the reverse proxy.

Indeed, that isn't ideal. I hoped the auto-detection would work in ~all cases but there are some edge cases like your setup that won't.

I'll add the option soon!

**Comment by lenormf** [comment]
Great! I'll let you close this issue once the option is in!

**Comment by hifi** [comment]
There you go :partying_face:

**Comment by lenormf** [comment]
Would you consider producing a release for that change? The CLI has new options and I'd like to be able to pull that change directly off of the Docker Hub if possible. Thanks!

**Comment by hifi** [comment]
I'll push a release later but you can use the `latest` tag right now if you want the changes from master.

**Comment by lenormf** [comment]
Actually, it's a bit weird that this option would be a bot command. The URL likely won't change arbitrarily once the bridge has been started, and would have to be re-configured after every time the bridge is stopped. Why not make this a CLI option?

**Comment by hifi** [comment]
The configuration is saved so it doesn't need resetting every time the bridge restarts.

Reasoning is that _all_ configuration other than what is needed to communicate with the homeserver is done in the control room by the bridge admin (with Heisenbridge). If you start the bridge the first time but the auto detection fails and you already have IRC connections open you don't need to restart and reconnect to update the media URL as it can be updated on-the-fly now.

**Comment by lenormf** [comment]
I understand, thanks!

**Comment by lenormf** [comment]
I confirm that the feature works as expected.
