### ISSUE TITLE
Re-send edited messages

### ISSUE THREAD

**Issue by lenormf** [hifi/heisenbridge#159]
Hi,

I got the following message after editing a message:

```
Editing messages is not supported on IRC, edited text was NOT sent.
```

I think the right behaviour would be to simply re-send the edited message, if that's possible?

Thanks!

**Comment by hifi** [comment]
Message edits were added to 1.2.0 🤔

**Comment by lenormf** [comment]
You're right it was a Docker mishap on my side, sorry for the noise.

**Comment by poVoq** [comment]
Any reason message edits might stop working?

I am sure I saw it working during my initial tests with Conduit, but now it definitely stopped working.

**Comment by hifi** [comment]
How do they stop working?

**Comment by poVoq** [comment]
Uhm, thinking about it further, maybe edits only work in bouncer mode but not in plumb mode?

**Comment by hifi** [comment]
Edit should work in both.
