### ISSUE TITLE
CTCP Ping is unimplemented.

### ISSUE THREAD

**Issue by AmandaCameron** [hifi/heisenbridge#164]
While it may be a valid argument that it's essentially useless for a bridged connection across protocol boundires, it may be worth implementing regardless.

I use a bot to issue a CTCP ping to my client to detect if my homelab's lost internet, though this might be less obsecure to notice now that the bridge will mark messages as read in the chat..

Note, while I was looking for the issue/PR that advanced the read recept, I noticed that there's #141 which also implements the PING CTCP, so not sure if there's something holding it up, but it would also close this.

**Comment by hifi** [comment]
I didn't merge it because it being on by default could be considered a security or abuse issue. I think I can rebase and merge it with an option to keep it disabled by default and let people enable it per network if they wish.
