### ISSUE TITLE
Trouble with the roomhandler when using ADDSERVER

### ISSUE THREAD

**Issue by grimneko** [hifi/heisenbridge#172]
Getting this error message when i work with the "ADDSERVER" command, adding a tls irc server.

heisenbridge          | Heisenbridge v1.5.0
heisenbridge          | Homeserver is publicly available at https://grimneko.de
heisenbridge          | ERROR:root:Ignoring exception from room handler. This should be fixed.
heisenbridge          | Traceback (most recent call last):
heisenbridge          |   File "/opt/heisenbridge/heisenbridge/__main__.py", line 150, in _on_mx_event
heisenbridge          |     await room.on_mx_event(event)
heisenbridge          |   File "/opt/heisenbridge/heisenbridge/room.py", line 85, in on_mx_event
heisenbridge          |     await handler(event)
heisenbridge          |   File "/opt/heisenbridge/heisenbridge/control_room.py", line 202, in on_mx_message
heisenbridge          |     await self.commands.trigger(command, tail)
heisenbridge          |   File "/opt/heisenbridge/heisenbridge/command_parse.py", line 95, in trigger
heisenbridge          |     await self.trigger_args(args, tail, allowed, forward)
heisenbridge          |   File "/opt/heisenbridge/heisenbridge/command_parse.py", line 79, in trigger_args
heisenbridge          |     await func(cmd_args)
heisenbridge          |   File "/opt/heisenbridge/heisenbridge/control_room.py", line 296, in cmd_servers
heisenbridge          |     proxy = f" through {server['proxy']}" if "proxy" in server and len(server["proxy"]) > 0 else ""
heisenbridge          | TypeError: object of type 'NoneType' has no len()

**Comment by hifi** [comment]
Indeed, the `SERVERS` command was broken for new servers since 1.4.0, fixed.

Fixed and thanks for reporting!
