### ISSUE TITLE
libera chat certfp auth needs "authenticate external" to authenticate with nickserv

### ISSUE THREAD

**Issue by darix** [hifi/heisenbridge#188]
irssi's implementation:

https://github.com/irssi/irssi/blob/master/src/irc/core/sasl.c#L80

**Comment by darix** [comment]
https://libera.chat/guides/certfp

**Comment by hifi** [comment]
This has been fixed in master with automatic AUTHENTICATE EXTERNAL by default and an override to disable it for OFTC.
