### ISSUE TITLE
Default room config for networks?

### ISSUE THREAD

**Issue by poVoq** [hifi/heisenbridge#197]
There are some configuration options for ROOM that would be nice to set network wide, like maxlines and pastebin support.

Is there a way to do that?

Thanks!

**Comment by hifi** [comment]
That's something I'd definitely want to do to make all configuration options that affect rooms/channels inheritable and configurable from top level. The current system is very crude and needs a complete redesign to make that work nicely so it hasn't been done yet but I'll keep this open.
