### ISSUE TITLE
feat: add twitch.tv/membership cap

### ISSUE THREAD

**Issue by szczot3k** [hifi/heisenbridge#199]
Hi,
would it be possible to add "twitch.tv/membership" as a supported capability?
As per `https://dev.twitch.tv/docs/irc/guide`:
`Membership: Adds membership state event data. By default, we do not send this data to clients without this capability.`

**Comment by szczot3k** [comment]
In general: unless this cap is requested, we don't get any users connected visible, so it breaks sync and makes it look really ugly.

**Comment by hifi** [comment]
Sure, that's probably fairly easy to do now with the generic cap support.
