### ISSUE TITLE
Any way to set this up to connect to multiple servers?

### ISSUE THREAD

**Issue by IeuanK** [hifi/heisenbridge#203]
I find the description to be very confusing. I currently use an IRC client connected to multiple servers through three separate ZNC instances. One network I am connected as X on ZNC X, another network I am connected as Y on ZNC Y, but both ZNC instances could also be connected to the same network, in some cases even joining the same channels.
I would like to attach all these to the same Matrix user, so that I can access them all from within Element. The experience I am looking for would be to have a group per connection, so one group called X-server1, one group called X-server2, one group called Y-server1 etc, giving me that same separation between channels and PMs on various IRC networks as I have now.

Is this possible? I would think that the bouncer mode would be correct for this, but can this map the same Matrix user to multiple different IRC users, or would this remove the separation I have going on?

**Comment by hifi** [comment]
Heisenbridge works like an IRC client so you can connect to multiple networks as a single Matrix user.

From the bridges perspective one ZNC connection is a server and channels are grouped to an optional Matrix space accordingly.

**Comment by IeuanK** [comment]
So I would just use it in bouncer mode then, not relay?

**Comment by hifi** [comment]
Yes definitely. Relay is for relaybot configuration which passes messages from Matrix through a single IRC user.

**Comment by IeuanK** [comment]
Thanks!

**Comment by IeuanK** [comment]
> From the bridges perspective one ZNC connection is a server and channels are grouped to an optional Matrix space accordingly.

How do I configure it to use spaces? After some messing about I got it connected to a network, working exactly as expected there, but the rooms I am invited to are all under my main space. Did I miss something obvious? Should I be creating a space manually, and then a channel in that space to act as control room?

Apologies if this is explained elsewhere, but I can't seem to figure this out

**Comment by hifi** [comment]
There's a `SPACE` command in each network room that creates a space and invites you in.

**Comment by IeuanK** [comment]
Oops, looks like I was on an older version of the docker image somehow. Updated and looks like it's working now!
