### ISSUE TITLE
Support for IRC colors

### ISSUE THREAD

**Issue by reinerh** [hifi/heisenbridge#210]
As an exmaple, some IRC channels contain bridge bots that relay messages from other networks to IRC. They prefix the messages with the nicks in color to make it easier to distinguish the users.

The color information is currently lost by heisenbridge.
It would be nice if this could be translated to equivalent coloring in matrix messages.

**Comment by hifi** [comment]
This only needs a proper IRC color escape parser. The current one strips away colors, poorly.

There were some efforts at doing this in the Matrix room but no one finished the work to a PR.

**Comment by namazso** [comment]
I wrote an [IRC color parser and converter in c++](https://gist.github.com/namazso/0b417ea1dc8a587a3b720b7fbfb8be44) to figure out parsing, but never got to finishing the python port. note that this is only for IRC->matrix and not the other way around, which is much harder

**Comment by hifi** [comment]
#225 fixed this.
