### ISSUE TITLE
DMs and network-specific bots appear in all managed spaces

### ISSUE THREAD

**Issue by jimeh** [hifi/heisenbridge#213]
I've got two separate IRC networks setup and connected, with the managed Space feature enabled.

However, the network-specific bots appear in both spaces, and all DM / people from both networks appear in the spaces for both networks.

I would expect the bot and people for a specific network, to only appear in the space for the network they belong to.

Might it be a bug related to the heisenbridge bot? As that also appears in both spaces, which is something I would expect.

**Comment by hifi** [comment]
This is unfortunately a bug/feature of Element clients that they show all DM-like rooms in all spaces if you and any participant of one is in a shared space. There's nothing I can do on bridge side within current design.
