### ISSUE TITLE
Strange blank notices from bot in control room

### ISSUE THREAD

**Issue by ahanselka** [hifi/heisenbridge#216]
I'm getting a decent amount of strange, empty `m.notice` messages in one of my IRC network control rooms. I'm not sure what info might be useful here, primarily because I'm not exactly sure what is happening to try to reproduce it and only one of my networks is doing it. The network in question seems to be running `UnrealIRCd-5.2.2-git`.

Here is a screenshot of the messages. They're blank so I guess not that interesting:

![Screen Shot 2022-03-29 at 16 46 50](https://user-images.githubusercontent.com/352106/160704640-a27413c1-5f72-46fe-ad0a-650551314380.png)

And here is the "view source" of one of the messages. I redacted the room_id and sender. I don't know if they're actually anything to worry about sharing, though. 

```json
{
  "content": {
    "body": "",
    "msgtype": "m.notice"
  },
  "origin_server_ts": 1648585303893,
  "sender": "@heisenbridge:<redacted>",
  "type": "m.room.message",
  "unsigned": {
    "age": 80
  },
  "event_id": "$Kx6XKEfX4-rTZohjw7p_PPVKqOJ-GpzlJoX5wr1h6J0",
  "room_id": "<redacted>"
}
```

**Comment by hifi** [comment]
If you could run Heisenbridge with `-vvv` you'll also see the raw IRC event. That would help me to understand what's going on.

Thanks!

**Comment by ahanselka** [comment]
@hifi Oh I should have known about that! 

This is what seems to be causing it:

```
Mar 30 14:16:21 matrix matrix-heisenbridge[3955368]: DEBUG:irc.client_aio:FROM SERVER: @+draft/typing=active;+typing=active;account=zomg;msgid=6Z3Ljy2nRHzqXkojWx0qPQ;time=2022-03-30T14:16:21.219Z :zomg!<redacted>@<redacted>TAGMSG #<redacted>
Mar 30 14:16:21 matrix matrix-heisenbridge[3955368]: DEBUG:irc.client:command: tagmsg, source: zomg!<redacted>@<redacted>, target: #<redacted>, arguments: [], tags: [{'key': '+draft/typing', 'value': 'active'}, {'key': '+typing', 'value': 'active'}, {'key': 'account', 'value': 'zomg'}, {'key': 'msgid', 'value': '6Z3Ljy2nRHzqXkojWx0qPQ'}, {'key': 'time', 'value': '2022-03-30T14:16:21.219Z'}]
```

Which seems to be related to [IRCv3 `typing` tag](https://ircv3.net/specs/client-tags/typing.html)

**Comment by ahanselka** [comment]
Ah good to know! It doesn't bother me that much but it would be cool to have someday if you ever have time! I don't think I know python well enough to do so, but I may take a look 🙂

**Comment by hifi** [comment]
You could start by making TAGMSG do nothing instead of flooding the network room. I've not had much time to work on Heisenbridge lately and that's fairly easy to do.
