### ISSUE TITLE
Bridge doesn't seem to handle action messages as initiating a private conversation.

### ISSUE THREAD

**Issue by sergaderg** [hifi/heisenbridge#223]
Just trying out the bridge for the first time, and someone tried to private message me with the initial message being a `/me ...` command. The bridge seemed to choke on this, just reporting 

`<user> requested CTCP ACTION (ignored)`

I then `QUERY`'d the user and asked what was going on, and they resent the message, which appeared fine once the room for that was already open.

I had autoquery enabled, and CTCPCFG disabled at the time, if that matters.

Ideally, this would open the room if autoquery was enabled, or at the very least, have the error message report the whole message, so I don't miss the context if I have to open the room manually.

**Comment by hifi** [comment]
That's indeed a bug, it should open the query if autoquery is on or show the real message if it isn't. This seems to be an edge case that isn't handled correctly.
