### ISSUE TITLE
Latest docker image seems broken

### ISSUE THREAD

**Issue by blastrock** [hifi/heisenbridge#228]
Hello,

I can't run the latest image, the container crashloops:

```
heisenbridge         | <coroutine object main at 0x7f4ce2f13b40>
heisenbridge         | sys:1: RuntimeWarning: coroutine 'main' was never awaited
heisenbridge         | RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

I am using image 7ae3e9101dcf

EDIT: I just discovered that I should use `hif1/heisenbridge:1` instead of `:latest` to have stable images :)

**Comment by hifi** [comment]
Indeed, the latest latest is straight from master, `hif1/heisenbridge:1` is the stable one.

#229 will fix this.
