### ISSUE TITLE
Don't touch my URLs!

### ISSUE THREAD

**Issue by piegamesde** [hifi/heisenbridge#239]
Heisenbridge should not do any processing with any tokens that might parse as URI. Currently, try sending an URL containing an @mention, and the '@' will disappear from the posted URL, rendering the link invalid.

**Comment by hifi** [comment]
Can you give an example where it detects a nickname within an URL? Are you using the latest version?

**Comment by piegamesde** [comment]
I am running Heisenbridge 1.13.1.

Example: `https://example.org/@piegames` turns up as `https://example.org/piegames`

**Comment by hifi** [comment]
Fixed in master. There was an old fallback for plain text messages which causes more harm than good.

**Comment by piegamesde** [comment]
Thanks
