### ISSUE TITLE
Strips @ from URLs making it impossible to share many Mastodon URLs

### ISSUE THREAD

**Issue by poVoq** [hifi/heisenbridge#247]
We found this strange issue that the bridge (in plumb mode) seems to strip @ signs from URLs, which is a problem when sharing links to Mastodon posts.

**Comment by reinerh** [comment]
Sounds like the same problem as #239, which has already been fixed?

**Comment by poVoq** [comment]
Ah, but I am pretty sure I updated to 0.14 shortly after it was released. Let me check.

**Comment by reinerh** [comment]
I think it's fixed only in git, not in a release.
