### ISSUE TITLE
Question: How to enable relaybot mode

### ISSUE THREAD

**Issue by pcmid** [hifi/heisenbridge#252]
I have two already existing rooms on matrix and irc and would like to bridge them. But I checked a lot of documentation and didn't find how to use the relaybot to join the rooms. 
When I went through the bot and logged into irc the bot created a new room and invited me but it wasn't what I wanted. Is there something I'm missing?

**Comment by hifi** [comment]
Use the `PLUMB` command in the network room. It will join the bot to a channel and a Matrix room.
