### ISSUE TITLE
Missing capabilities message-tags, chghost, znc.in/self-message

### ISSUE THREAD

**Issue by ojoeth** [hifi/heisenbridge#253]
When connecting to Esper.net, the server requests some capabilities which Heisenbridge does not yet support. 

```
Connecting to [irc.esper.net:6697](http://irc.esper.net:6697/)...
Capabilities wanted: message-tags, chghost, [znc.in/self-message](http://znc.in/self-message)
Disconnected, reconnecting in 1800 seconds...
```

**Comment by hifi** [comment]
The wanted list works the other way around, it's what Heisenbridge supports and it lists them on connect time.

I think there's some other issue with your connection, like using TLS port without having --tls added for the server in Heisenbridge.

**Comment by ojoeth** [comment]
Oh I see! That worked :)
