### ISSUE TITLE
Feature Request: Add setting to allow users from other homeservers to use the bot

### ISSUE THREAD

**Issue by Froggo8311** [hifi/heisenbridge#272]
I was thinking something along the lines of how the mautrix bridges work, with allowing a whitelist of servers or a regex to match for. I have a homeserver set up that I use mainly for hosting AS bots and would like to use those bots from my main matrix instance I use, inclding heisenbridge.

**Comment by hifi** [comment]
Use `ADDMASK` to allow users from other homeservers in your DM with the bridge bot. See `ADDMASK -h` for examples.

**Comment by Froggo8311** [comment]
Oh, okay, thank you :)

**Comment by Froggo8311** [comment]
@hifi It seems to only partially work- the first message I send to the room from the remote server is processed, but none of the others are. It doesn't seem like there's anything useful in stdout, either. The bot still works from the user on the local HS.

**Comment by Froggo8311** [comment]
Actually, it seems like no messages I send are processed. This is interesting...

**Comment by Froggo8311** [comment]
Ooooookay, so it seems to work, it's just unbearably slow. Any ideas what I could do to fix that?

**Comment by Froggo8311** [comment]
[Turned off ratelimiting](https://github.com/matrix-org/synapse/issues/6286#issuecomment-661773399) for the remote user, and I think it worked... Thanks for your help.
