### ISSUE TITLE
Option to disable away notices

### ISSUE THREAD

**Issue by jhass** [hifi/heisenbridge#274]
I'm really not interested in away notifications for most servers, could we have an option to disable them?

**Comment by hifi** [comment]
What away notifications? The ones server sends you when you talk to someone who is away?

**Comment by jhass** [comment]
No, the notice messages in the server room. I believe they're generated from https://github.com/hifi/heisenbridge/blob/06d2d445edd891ab06e95fe8cf7533fd30328b8a/heisenbridge/network_room.py#L1958-L1961

**Comment by hifi** [comment]
`CAPS --remove away-notify` in network room and then reconnect.

**Comment by jhass** [comment]
Ah thanks. I guess enabling this I was hoping for the away status to show up on the user profile/room member list somehow.
