### ISSUE TITLE
option to hide join/part messages

### ISSUE THREAD

**Issue by craftyguy** [hifi/heisenbridge#292]
The backlog for IRC rooms I am in is often filled with huge numbers of these join/part messages that I would like to hide, but I don't see any obvious way to do that:

<details><summary>screenshot showing joins/parts</summary>

![2024-07-17-084602_grim](https://github.com/user-attachments/assets/af407505-b898-4566-b5e6-9de5327e9b94)

</details>

Some matrix clients let you collapse that mess, others don't, and I'd rather just not see them at all anywhere without having to rely on being able to do it client-side.

**Comment by BtbN** [comment]
You can't hide them server side, the users need to join the room after all so they can write there.
In theory you could never part them, but that would build up a huge mess quickly.

**Comment by BtbN** [comment]
The message you see is your client generating a message for the users joining/leaving. Hence hiding them can only be done on the client side.
Heisenbridge is not explicitly printing that.
