### ISSUE TITLE
Media proxy does not seem to be getting used

### ISSUE THREAD

**Issue by spantaleev** [hifi/heisenbridge#294]
In [9d11271d59a054](https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/9d11271d59a054ee3357dc90e29702c951c537d8), I've worked on adapting [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) to your [v1.15.0](https://github.com/hifi/heisenbridge/releases/tag/v1.15.0) release which is supposed to run a media proxy serving `/_heisenbridge/media/*` paths and being exposed publicly under `media_url`.

Our intention (expectation) is to:

- have the playbook expose Heisenbridge at a `/heisenbridge` path prefix by default (e.g. `media_url = https://matrix.DOMAIN/heisenbridge`). This is configurable - some users may wish to dedicate a hostname to Heisenbridge and not use a path prefix (e.g. `media_url = https://heisenbridge.DOMAIN`)
- have Heisenbridge generate URLs like this: `{media_url}/_heisenbridge/media/something`. Examples:
  - (Matrix hostname + path prefix) `https://matrix.DOMAIN/heisenbridge/_heisenbridge/media/something`
  - (dedicated hostname, without path prefix) `https://heisenbridge.DOMAIN/_heisenbridge/media/something`
- have the playbook's reverse-proxy strip the optional path prefix (e.g. `/heisenbridge`) and pass whatever remains (e.g. `/_heisenbridge/media/*`) to the Heisenbridge server

It seems like currently Heisenbridge still generates URLs destined for the Matrix Media API, looking like this: `{media_url}/_matrix/media/v3/download/DOMAIN/FILE_ID/FILE_NAME`. Unless `media_url` is pointed to the homeserver URL, this cannot work.

-------

Is there something else that needs to be done to enable the media proxy functionality? Is it possible only enabled for certain media and not other?

Perhaps us adding an additional `/heisenbridge` prefix and putting it in the `media_url` configuration key is not compatible with Heisenbridge's expectations.

It's probably most straightforward if Heisenbridge always proxied all media, instead of constructing 2 different types of URLs (sometimes leading to the Media API, sometimes leading to the media proxy).

**Comment by tulir** [comment]
There's only one way of constructing URLs, not two. However, the media path is configurable too (`heisenbridge` -> `media_path`)
