### ISSUE TITLE
Make user ID prefix configurable

### ISSUE THREAD

**Issue by tulir** [hifi/heisenbridge#34]
Some people may want different prefixes than `@irc_`, so it shouldn't be hardcoded. Parsing the regex from the registration file (e.g. user id prefix = text before `.+` or `.*` in regex) is probably the best solution if you don't want to add any other config.

**Comment by hifi** [comment]
That's fair and I was thinking the same that it should pull it from the reg file.

**Comment by hifi** [comment]
Should be fixed in master.
