### ISSUE TITLE
Single control/admin room for all networks 

### ISSUE THREAD

**Issue by hifi** [hifi/heisenbridge#39]
This makes it more inline with IRC clients like irssi and weechat where messages from all networks are shown in the status window. 

This is a major refactor but doable.

**Comment by hifi** [comment]
With spaces and some of the proposed workflows I'm thinking it may actually be better to keep the current design and just organize rooms like that to "hide" the network room.

**Comment by sumnerevans** [comment]
Just want to put in my two cents, I really like the existing design. It allows me to keep things more organized.

**Comment by hifi** [comment]
I'm going to favor spaces support over this as it doesn't break the existing design as this would require major refactoring.
