### ISSUE TITLE
Spaces support

### ISSUE THREAD

**Issue by ptman** [hifi/heisenbridge#49]
Group rooms into spaces

**Comment by piegamesde** [comment]
Do you mean, having one space per IRC server or something?

**Comment by hifi** [comment]
Would the proposed MVP that was talked on Matrix be okay where the bridge will not create spaces but would create new rooms in existing spaces where the network room is and the bridge has access to? I'd be interested to see that as a PR :grin:

**Comment by ptman** [comment]
Rooms can belong to several spaces. Are we sure it makes sense to add rooms to all the spaces the control room is in?

**Comment by hifi** [comment]
If channels and PMs go in spaces the _network_ room is in that wouldn't be too off, no? New network rooms would default to spaces the control room is, though that would only cover spaces it's an administrator of.

**Comment by sumnerevans** [comment]
I think the key is that Heisenbridge has to be an admin of the space. If you don't want to use any spaces features, you just don't make the bot an admin.

**Comment by hifi** [comment]
#187 implemented network level bridge controlled spaces, this should be enough to satisfy most use cases.
