### ISSUE TITLE
Support arbitrary commands on connect

### ISSUE THREAD

**Issue by jgoerzen** [hifi/heisenbridge#53]
On some networks, for instance, I'd send `MODE mynick +R` to prevent myself from getting spam.  It would be great to be able to send more than one command on connect (beyond just the one to identify to nickserv).  Thanks!

**Comment by Mikaela** [comment]
While I agree that this would be a nice feature (for e.g. setting umodes), you could `password username:password` to get authenticated on most of networks.

**Comment by hifi** [comment]
Yeah it's a good addition to have multiple command support. I was thinking of having a list of commands with arguments separated with `;` instead of using raw irc by default.

So something like `AUTOCMD umode +R; msg some-bot auth foo bar; oper me obey`

**Comment by hifi** [comment]
AUTOCMD was updated to support multiple commands. UMODE was also added as a network of level command so it always uses the correct nick.
