### ISSUE TITLE
Filtering events coming from yourself, like messages typed in another znc session

### ISSUE THREAD

**Issue by warthog9** [hifi/heisenbridge#62]
When using znc to act as the intermediary to the actual IRC network, if you type something from one of the other connected actual IRC clients to znc, the message shows back in heisenbridge/matrix fine but shows up as coming from username!ident@host.name.tld instead of "me" or a virtual user shortname

On other clients it ends up filling in as having come from "me"

This is really just a cosmetic fix, as the message does come back and it's obvious in matrix that something was written on another connection on znc.

**Comment by hifi** [comment]
Yeah, this is reasonable. I need to reproduce this locally so I can also see that the fix works even when changing nicks from server side nick enforcement, znc nick enforcement and client (heisen) nick change.

**Comment by hifi** [comment]
So if I filter them out they will not show up on Matrix at all, is that the intention here?

**Comment by warthog9** [comment]
Yeah, the intention wasn't to lose the information, just try and get it formatted better(?)

Right now it comes back looking like:
    Heisenbridge
    Message from ircnick!ident@connectedfrom.example.tld: <message>
and it feels like it just gets lost, and is hard to scan, and it's greyed out like it was a join/part message.

Your "You said:" would probably work pretty well
