### ISSUE TITLE
Feature request: add ZWSP after the first letter of username and domain

### ISSUE THREAD

**Issue by Mikaela** [hifi/heisenbridge#63]
ZWSP is a zero-width space and having it in the messages sent by the relaybot would avoid pinging users on IRC when they have the same nick on both sides. E.g. on the main room I am `@mikaela:feneas.org` and on LiberaChat I am `Mikaela` so I get pinged whenever I say something at Matrix.

I would like the bot to refer to me as `@mZWSPikaela:fZWSPeneas.org`, so I wouldn't get pinged even if my MXID contained my domain (I would likely be `@mikaela:mikaela.info` if I was running my own homeserver and such MXIDs aren't uncommon).

**Comment by Mikaela** [comment]
It would be nice to do this also on the Matrix side, because now it pings me whenever showing people on IRC and also topic setters on restart 😬

**Comment by hifi** [comment]
Though on Matrix side it may be inteded for IRC users to be able to ping.

I'm not exactly sure if adding this would be a good addition.

**Comment by Mikaela** [comment]
On IRC side I don't need to ping myself every time I message at Matrix and on Matrix I don't think topic setter or names lists are supposed to ping the Matrix user upon reconnection.
