### ISSUE TITLE
[tracking issue] create actual releases

### ISSUE THREAD

**Issue by sumnerevans** [hifi/heisenbridge#66]
I know that @hifi has mentioned he wants things to stabilize a bit before this.

It would be especially helpful for packagers. For example, NixOS currently has the version set to `unstable-2021-05-23` (https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/heisenbridge/default.nix#L5)

**Comment by hifi** [comment]
Would be nifty if versioning was handled automatically from git tags and hashes so far I could just create a release tag and push.

**Comment by hifi** [comment]
Versioning is now in place, just need to tag them.
