### ISSUE TITLE
Handle replies somehow

### ISSUE THREAD

**Issue by hifi** [hifi/heisenbridge#67]
Possibly prepend the message with the original sender so it looks somewhat follow-able on IRC?

**Comment by sumnerevans** [comment]
The proposed solution is what matrix-appservice-irc does. I think that it's probably the best option. Note that matrix-appservice-irc only sends some of the replied-to message, not the entire thing.

**Comment by hifi** [comment]
It's not very irc-y to include a snippet, though. It just creates more clutter.

**Comment by sumnerevans** [comment]
I think it's also passable to just do an `@mention` with the sender who was replied to.
