### ISSUE TITLE
Support ident (oidentd forwarding ?)

### ISSUE THREAD

**Issue by Mikaela** [hifi/heisenbridge#73]
Currently Heisenbridge (or the lab) doesn't seem to be running an identd so networks that care about it prefix an `~` in front of the username.

I think it should support getting/sending responses through oidentd forwarding for a couple of reasons:

* Oidentd is a well known service that is easy to setup and runs on the ident port 113 without the need or figuring out how to give Heisenbridge access to a privileged port.
* Traditional IRC networks generally care about ident and require it to exist and be unchanging before granting out connection limit increases or I-lines or whatever you wish to call them as.
  * Last, but not least, even without those, IRC networks generally [grant more connections to hosts that have identd running, for example Solanum IRCd](https://github.com/solanum-ircd/solanum/blob/dfeba6556304bc6ee712b484a9730cf998d4a4d7/doc/reference.conf#L223-L236) which Libera.Chat uses and IRCnet (judging by some of their MOTDs).

I have no idea how ident works other than using TCP port 113 and particularly IRCnet letting you faster in if you either have it or block it by rejecting traffic to it in firewall, but maybe some of these links could be of help:

* oidentd homepage: https://oidentd.janikrabe.com/
    * documentation on forwarding: https://janikrabe.com/projects/oidentd/docs/nat/forwarding/
* TheLounge (webIRC client) documentation on this: https://thelounge.chat/docs/guides/identd-and-oidentd#using-oidentd-to-forward-requests-to-the-built-in-server
* TheLounge PR bringing their feature in: https://github.com/thelounge/thelounge/pull/804/files (warning: it may be more recent in the actual codebase and is in NodeJS which I don't speak)

**Comment by hifi** [comment]
So answering the issue as well that we have an identd implementation but it sometimes fails and I don't know why yet.
