### ISSUE TITLE
Document how to make heisenbridge server admin

### ISSUE THREAD

**Issue by dasJ** [hifi/heisenbridge#86]
Document what to do when heisenbridge shows

> WARNING:root:We (@heisenbridge:example.com) are not a server admin, inviting puppets manually is required which is slightly slower.

**Comment by hifi** [comment]
As I said in Matrix, I'll change this to be less intimidating as it's not really required at all and I don't use it myself. I'll move this message to info stream from warning so it's not shown by default.
