### ISSUE TITLE
when server bans you, heisenbridge continues to try to reconnect to same server

### ISSUE THREAD

**Issue by keithah** [hifi/heisenbridge#98]
I would expect heisenbridge to notice when a server response is 'banned' and not retry and remove it from retry logic for everyone.

**Comment by hifi** [comment]
There's nothing special about the way it kills the connection when you are banned but it could/should rotate to the next configured server if there is more than one.

**Comment by hifi** [comment]
Fixed in d249754c8993e94f8547a36a1be5627daf167d48 with server rotation
