### ISSUE TITLE
No way to choose which server is used

### ISSUE THREAD

**Issue by keithah** [hifi/heisenbridge#99]
As far as I can tell, you can't force a specific server, so if one stops working (ban, fails ident, etc) it will still continue to try it.

It'd be nice to be able to use open to specific an exact server.

**Comment by hifi** [comment]
Fixing #98 should help with this if the admin configures more than one server in the rotation.

**Comment by hifi** [comment]
Fixed in d249754c8993e94f8547a36a1be5627daf167d48 with server rotation
